config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    get 'errors/show'
    
    
    resources :exercices
      
    resources :sessions
    resources :modes

    namespace :conjugaisons do
      resources :verbes do
        collection do
          get 'search'
          get 'autocomplete'
        end
      end
    end
    
    get 'home/recherche_verbe'
    
    root to: 'home#main'
    get 'home/main'
    
    get ':status', to: 'errors#show', constraints: {status: /\d{3}/ }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def main
  end
  
  def recherche_verbe
    if params[:verb]
      verb = params[:verb].to_s
      @verbs = TenseEntry.search_verb(verb)
    else
      @verbs = []
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/main.html.erb
<% provide(:title, t('.title') ) %>
<% provide(:description, t('.description') ) %>
<% provide(:keywords_french, "conjugaison, conjuguer, définition, verbe, francaise, francais, conjuguer, synonyme, synonymes, verbes, indicatif, subjonctif, impératif, infinitif, conditionnel, participe, gérondif, présent, imparfait, passé composé, passé simple, futur, futur simple, futur antérieur, passé")%>
<% provide(:keywords_english, "conjugation, conjuguer, definition, verb, french, conjugate, synonym, synonyms, verbs, indicatif, subjonctif, impératif, infinitif, conditionnel, participe, gérondif, présent, imparfait, passé composé, passé simple, futur, futur simple, futur antérieur, plus que parfait, passé antérieur, passé")%>


<div class="row">
	<div class="col-lg-6 col-md-6 col-xs-10 col-md-offset-3 col-lg-offset-3 col-xs-offset-1 search-container">

		<h1 class="page-header text-center main-page-title box-big-title"><%= t('.h1') %></h1>
		<br />
		<%= render partial: "conjugaisons/verbes/search_form" %>

		<hr />

	</div>
</div>

<hr />

<div class="row">
	<div class="col-lg-6 col-md-6 col-xs-10 col-md-offset-3 col-lg-offset-3 col-xs-offset-1">

		<br />
		<% if flash[:notice] %>
		<div class="col-md-12 nadvence-box">
			<div>
				<h4 class="text-warning text-center"> <%= notice %> </h4>

			</div>
		</div>
		<% end %>
		
	
		<div class="col-md-6">
			<div class="nadvence-box">
			<div class="box-title text-center">
				<%= link_to t('.verbs_list'), conjugaisons_verbes_path %>
				
				
			</div>
			</div>
		</div>
		
		<div class="col-md-6">
			<div class="nadvence-box">
			<div class="box-title text-center">
				<%= link_to t('.search_verb'), home_recherche_verbe_path %>
				
				
			</div>
			</div>
		</div>
			
			<div class="col-md-12 nadvence-box">
			<div class="verbs-links"><h3><%= t('.common_verbs') %></h3>
				<a href="<%= conjugaisons_verbe_path(:id => "avoir") %>">avoir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "donner") %>">donner</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "reflechir") %>">réfléchir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "asseoir") %>">asseoir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "remplir") %>">remplir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "boire") %>">boire</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "parler") %>">parler</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "rejoindre") %>">rejoindre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "partir") %>">partir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "rire") %>">rire</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "ecrire") %>">écrire</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "transmettre") %>">transmettre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "joindre") %>">joindre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "resoudre") %>">résoudre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "devoir") %>">devoir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "savoir") %>">savoir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "apprendre") %>">apprendre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "croire") %>">croire</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "reussir") %>">réussir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "venir") %>">venir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "vivre") %>">vivre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "courir") %>">courir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "inclure") %>">inclure</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "jouer") %>">jouer</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "rendre") %>">rendre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "prendre") %>">prendre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "voir") %>">voir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "plaire") %>">plaire</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "penser") %>">penser</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "souhaiter") %>">souhaiter</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "etre") %>">être</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "faire") %>">faire</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "aller") %>">aller</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "pouvoir") %>">pouvoir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "vouloir") %>">vouloir</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "permettre") %>">permettre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "aimer") %>">aimer</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "creer") %>">créer</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "mettre") %>">mettre</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "essayer") %>">essayer</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "appeler") %>">appeler</a> -
				<a href="<%= conjugaisons_verbe_path(:id => "comprendre") %>">comprendre</a>
			</div>
		</div>
		
		
		
		<div class="col-md-12 nadvence-box">
			<div class="box-title text-center">
				<%= t('.partners_list') %>
				
				
			</div>
			<a href="http://www.poesie-et-poeme.fr">Poésies francaises</a> - 
			<a href="http://www.combien-de-calories.com">Combien de calories</a>
			</div>
	</div>
</div>

app/views/home/recherche_verbe.html.erb
<% provide(:title, t('.title') ) %>
<% provide(:description, t('.description') ) %>

<div class="row">
	<div class="col-lg-6 col-md-6 col-xs-10 col-md-offset-3 col-lg-offset-3 col-xs-offset-1">

		<h1 class="page-header text-center first-title box-big-title"><%= t('.h1') %></h1>
		<br />
		<div class="nadvence-box">
			<span class="lead"><%= t('.explanation') %></span>
		</div>
		<br />
		<%= form_tag({controller: "home", action: "recherche_verbe"}, method: "get", class: "form") do %>
		<div class="col-md-12">

			<%= text_field_tag(:verb, params[:verb], :id => "search", :class => "form-control search-input", :autocomplete => "off", :autofocus=>"autofocus", :title => "Verbe") %>

		</div>
		<div class="col-md-12 text-center">
			<br />
			<%= submit_tag(t('.button'), :class => "btn btn-warning btn-lg nadvence-family") %>
		</div>

		<% end %>

		<hr />

	</div>
</div>

<hr />

<div class="row">
	<div class="col-lg-6 col-md-6 col-xs-10 col-md-offset-3 col-lg-offset-3 col-xs-offset-1">

		<br />

		<% if params[:verb]%>
		<div class="col-md-12 nadvence-box">
			<h1 class="text-center page-header box-title text-warning"> <%= t('.result') %> : <b><%= params[:verb].to_s%></b></h1>
			<div>

				<% @verbs.each do |verb| %>
				<h3 class="text-center"><%= link_to verb.content.to_s, conjugaisons_verbe_path(verb)%> <small> <%= verb.definition.try(:html_safe)%> </small></h3>
				<% end %>

				<% if @verbs.empty?%>
				<%= t('.no_verb') %>
				<% end %>
			</div>
			<br />
			
		</div>
		<% end %>
	</div>
</div>