config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    get 'errors/show'
    
    
    resources :exercices
      
    resources :sessions
    resources :modes

    namespace :conjugaisons do
      resources :verbes do
        collection do
          get 'search'
          get 'autocomplete'
        end
      end
    end
    
    get 'home/recherche_verbe'
    
    root to: 'home#main'
    get 'home/main'
    
    get ':status', to: 'errors#show', constraints: {status: /\d{3}/ }
  end

end

app/models/mode.rb
# == Schema Information
#
# Table name: modes
#
#  id           :integer          not null, primary key
#  name         :text
#  description  :text
#  markup       :text
#  created_at   :datetime
#  updated_at   :datetime
#  tenses_count :integer          default(0)
#  order        :integer          default(0)
#

class Mode < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  
  has_many :tenses
  
  
  def self.update_tenses_count
    self.find_each do |mode|
      mode.update(:tenses_count => mode.tenses.count)
    end
  end
  
end

app/controllers/modes_controller.rb
class ModesController < ApplicationController
  before_action :set_mode, only: [:show, :edit, :update, :destroy]
  before_filter :no_access

  # GET /modes
  # GET /modes.json
  def index
    @modes = Mode.all
  end
  
  

  # GET /modes/1
  # GET /modes/1.json
  def show
  end

  # GET /modes/new
  def new
    @mode = Mode.new
  end

  # GET /modes/1/edit
  def edit
  end

  # POST /modes
  # POST /modes.json
  def create
    @mode = Mode.new(mode_params)

    respond_to do |format|
      if @mode.save
        format.html { redirect_to @mode, notice: 'Mode was successfully created.' }
        format.json { render :show, status: :created, location: @mode }
      else
        format.html { render :new }
        format.json { render json: @mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modes/1
  # PATCH/PUT /modes/1.json
  def update
    respond_to do |format|
      if @mode.update(mode_params)
        format.html { redirect_to @mode, notice: 'Mode was successfully updated.' }
        format.json { render :show, status: :ok, location: @mode }
      else
        format.html { render :edit }
        format.json { render json: @mode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modes/1
  # DELETE /modes/1.json
  def destroy
    @mode.destroy
    respond_to do |format|
      format.html { redirect_to modes_url, notice: 'Mode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mode
      @mode = Mode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mode_params
      params.require(:mode).permit(:name, :description, :markup, :order)
    end
end

app/helpers/modes_helper.rb
module ModesHelper
end

app/views/modes/_form.html.erb
<%= form_for(@mode) do |f| %>
  <% if @mode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mode.errors.count, "error") %> prohibited this mode from being saved:</h2>

      <ul>
      <% @mode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :markup %><br>
    <%= f.text_area :markup %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modes/edit.html.erb
<h1>Editing mode</h1>

<%= render 'form' %>

<%= link_to 'Show', @mode %> |
<%= link_to 'Back', modes_path %>

app/views/modes/index.html.erb
<h1>Listing modes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Markup</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modes.each do |mode| %>
      <tr>
        <td><%= mode.name %></td>
        <td><%= mode.description %></td>
        <td><%= mode.markup %></td>
        <td><%= mode.order %></td>
        <td><%= link_to 'Show', mode %></td>
        <td><%= link_to 'Edit', edit_mode_path(mode) %></td>
        <td><%= link_to 'Destroy', mode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mode', new_mode_path %>

app/views/modes/new.html.erb
<h1>New mode</h1>

<%= render 'form' %>

<%= link_to 'Back', modes_path %>

app/views/modes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mode.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @mode.description %>
</p>

<p>
  <strong>Markup:</strong>
  <%= @mode.markup %>
</p>

<p>
  <strong>Order:</strong>
  <%= @mode.order %>
</p>

<p>Temps</p>

<% @mode.tenses.each do |t|%>
<%= t.name %> |

<% end %>

<%= link_to 'Edit', edit_mode_path(@mode) %> |
<%= link_to 'Back', modes_path %>