config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)" do
    get 'errors/show'
    
    
    resources :exercices
      
    resources :sessions
    resources :modes

    namespace :conjugaisons do
      resources :verbes do
        collection do
          get 'search'
          get 'autocomplete'
        end
      end
    end
    
    get 'home/recherche_verbe'
    
    root to: 'home#main'
    get 'home/main'
    
    get ':status', to: 'errors#show', constraints: {status: /\d{3}/ }
  end

end

app/models/exercice.rb
# == Schema Information
#
# Table name: exercices
#
#  id              :integer          not null, primary key
#  question_number :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Exercice < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  has_many :tense_entries, :through => :questions
  
  has_many :exercicings, dependent: :destroy
  has_many :tenses, :through => :exercicings
  
  attr_writer :tenses_associated
  after_create :save_tenses_associated
  after_create :create_questions
  
  validates :question_number, presence: true, :numericality => { :greater_than => 0, :less_than_or_equal_to => 100 }
  validates :tenses_associated, presence: true
  
  def tenses_associated
    @tenses_associated || self.tenses.pluck(:id)
  end
  
  def save_tenses_associated
    keys = tenses_associated.keys
    keys.each do |k|
      t = Tense.find_by(:id => k.to_i)
      self.tenses << t
    end
  end
  
  def create_questions
    tense_entries = TenseEntry.joins(:tense).where('tenses.id IN (?)', self.tenses.pluck(:id)).order('RANDOM ()').limit(self.question_number)
    self.tense_entry_ids = tense_entries.pluck(:id)
  end
  
  def score(answers)
    score = 0
    tab = answers.to_a
    tense_entries = self.tense_entries
    tab.each do |q|
      t = tense_entries.find(q[0].to_i)
      if t.correct_answer(q[1])
        score += 1
      end
    end
    return score
  end
  
end

app/controllers/exercices_controller.rb
class ExercicesController < ApplicationController
  before_action :set_exercice, only: [:show, :edit, :update, :destroy]
  before_filter :no_access, only: [:index, :edit, :destroy, :update]

  # GET /exercices
  # GET /exercices.json
  def index
    @exercices = Exercice.all
  end

  # GET /exercices/1
  # GET /exercices/1.json
  def show
    if params[:correction] == "true"
      @correction = true
      @score = @exercice.score(params[:answers])
    else
      @correction = false
    end
    
  end

  # GET /exercices/new
  def new
    @exercice = Exercice.new
  end

  # GET /exercices/1/edit
  def edit
  end

  # POST /exercices
  # POST /exercices.json
  def create
    @exercice = Exercice.new(exercice_params)

    respond_to do |format|
      if @exercice.save
        format.html { redirect_to @exercice, notice: 'Exercice was successfully created.' }
        format.json { render :show, status: :created, location: @exercice }
      else
        format.html { render :new }
        format.json { render json: @exercice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercices/1
  # PATCH/PUT /exercices/1.json
  def update
    respond_to do |format|
      if @exercice.update(exercice_params)
        format.html { redirect_to @exercice, notice: 'Exercice was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercice }
      else
        format.html { render :edit }
        format.json { render json: @exercice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercices/1
  # DELETE /exercices/1.json
  def destroy
    @exercice.destroy
    respond_to do |format|
      format.html { redirect_to exercices_url, notice: 'Exercice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercice
      @exercice = Exercice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercice_params
      params.require(:exercice).permit!
    end
end

app/helpers/exercices_helper.rb
module ExercicesHelper
end

app/views/exercices/_form.html.erb
<%= form_for(@exercice, :class => "form-horizontal") do |f| %>
<% if @exercice.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@exercice.errors.count, "error") %> prohibited this exercice from being saved:</h2>

	<ul>
		<% @exercice.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<br />

<div class="col-md-12">
	<div class="col-md-6">
		<div class="form-group">
			<%= f.label :question_number, "Nombre de questions", :class => "col-sm-3 control-label" %>
			<div class="col-sm-9">
				<%= f.number_field :question_number, :class => "form-control" %>
			</div>
		</div>
	</div>
</div>

<div class="col-md-12">
<h2 class="page-header">Quels temps souhaitez vous travailler ?</h2>

<% Mode.all.each do |mode| -%>

<div class="col-md-4">
	<h2 class="page-header"><%= mode.name %></h2>
	<% mode.tenses.each do |tense|%>
	
	<div class="checkbox">
		<label> <%= check_box_tag "exercice[tenses_associated][#{tense.id}]", 1, false, :class => "" %>
			<%= tense.name %> </label>
	</div>

	

	<% end %>
</div>
<% end -%>

</div>

<div class="col-md-12 text-center">
	<div class="actions">
		<%= f.submit("Créer un exercice", :class => "btn btn-success btn-lg") %>
	</div>
</div>
<% end %>

app/views/exercices/edit.html.erb
<h1>Editing exercice</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercice %> |
<%= link_to 'Back', exercices_path %>

app/views/exercices/index.html.erb
<h1>Listing exercices</h1>

<table>
  <thead>
    <tr>
      <th>Question number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercices.each do |exercice| %>
      <tr>
        <td><%= exercice.question_number %></td>
        <td><%= link_to 'Show', exercice %></td>
        <td><%= link_to 'Edit', edit_exercice_path(exercice) %></td>
        <td><%= link_to 'Destroy', exercice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercice', new_exercice_path %>

app/views/exercices/new.html.erb
<% provide(:title, "Nouvel exercice de conjugaison") %>
<% provide(:description, "Exercices de conjugaison française. Travaillez les temps et les modes que vous souhaitez." ) %>

<div class="container">
	<h1 class="page-header text-center nadvence-box box-big-title">Nouvel exercice</h1>

	<%= render 'form' %>

</div>

app/views/exercices/show.html.erb
<% provide(:title, "Exercice de conjugaison") %>
<% provide(:description, "Exercices de conjugaison française. Travaillez les temps et les modes que vous souhaitez." ) %>

<div class="container">
	<div class="col-md-12">
		<h1 class="page-header text-center nadvence-box box-big-title">Exercice de conjugaison</h1>

		<div class="nadvence-box">
			<p>
				<strong>Nombre de questions:</strong>
				<%= @exercice.question_number %>
			</p>

			<p>
				<strong>Temps demandés:</strong>
				<%= @exercice.tenses.map{|t| t.name + " (" + t.mode.name + ")" }.join(' - ')  %>
			</p>

		</div>

		<% if !@correction %>

		<h2 class="nadvence-color text-center nadvence-family page-header">Questions</h2>
		<%= form_tag({controller: "exercices", action: "show"}, method: "get", class: "form-horizontal") do %>
		<% @exercice.tense_entries.each do |tense_entry| %>
		<div class="well">
			<h4> Verbe : <%= link_to tense_entry.verb.content, conjugaisons_verbe_path(tense_entry.verb) %> - <span class="text text-info">Temps :</span> <%= tense_entry.tense.name%> - <span class="text text-warning">Mode :</span> <%= tense_entry.tense.mode.name%>  - <span class="text text-danger"> Personne : </span><%= tense_entry.order_to_human%> </h4>
			<div class="form-group">
				<%= label_tag("answers[#{tense_entry.id}]", "Votre réponse:", :class => "col-sm-2 control-label") %>
				<div class="col-sm-6">
					<%= text_field_tag("answers[#{tense_entry.id}]", nil, :class => "form-control") %>
				</div>
			</div>
		</div>
		<% end %>

		<%= hidden_field_tag(:exercice_id, @exercice.id) %>
		<%= hidden_field_tag(:correction, true) %>

		<div class="text-center">
			<%= submit_tag("Correction", :class => "btn btn-success btn-lg") %>
		</div>
		<% end %>

		<% else%>

		<h2 class="nadvence-color text-center nadvence-family page-header">Questions (Votre score : <%= @score %> / <%= @exercice.question_number %>)</h2>

		<% @exercice.tense_entries.each do |tense_entry| %>
		<div class="well">
			<h4> Verbe : <%= link_to tense_entry.verb.content, conjugaisons_verbe_path(tense_entry.verb) %> - <span class="text text-info">Temps :</span> <%= tense_entry.tense.name%> - <span class="text text-warning">Mode :</span> <%= tense_entry.tense.mode.name%>  - <span class="text text-danger"> Personne : </span><%= tense_entry.order_to_human%> </h4>
			<div class="form-group">

				<% if tense_entry.correct_answer(params["answers"][tense_entry.id.to_s.to_sym]) %>
				<h4>Votre réponse: <span class="text text-success">"<%= params["answers"][tense_entry.id.to_s.to_sym]%>"</span> | <span class="text text-success"> Correction : <%= tense_entry.important_content %></span> <span class="text text-success"><i class="fa fa-check-circle"></i></span></h4>
				<% else %>
				<h4>Votre réponse: <span class="text text-danger">"<%= params["answers"][tense_entry.id.to_s.to_sym]%>"</span> | <span class="text text-success"> Correction : <%= tense_entry.important_content %></span> <span class="text text-danger"><i class="fa fa-times-circle"></i></span></h4>

				<% end %>

			</div>
		</div>

		<% end %>

		<div class="text-center">
			<%= link_to "Recommencer l'exercice", @exercice, :class => "btn btn-info btn-lg"%>
			<%= link_to "Nouvel exercice", new_exercice_path, :class => "btn btn-warning btn-lg"%>
		</div>
		<%end %>

	</div>
</div>